### ISSUE TITLE
Monsters with wrong HP or AC

### ISSUE THREAD

**Issue by Lakeyzer** [HarmlessHarm/HarmlessKey#11]
Sometimes monsters are added to an encounter with the wrong HP or AC

**Comment by JTPenguin** [comment]
I'm experiencing this issue currently. When I add a monster, it seems like it is taking the HP and AC from another monster. For example, when I add a Drow, it ends up with the HP/AC of a Drider.

**Comment by Lakeyzer** [comment]
Thanks for noticing, we fixed it.
