### ISSUE TITLE
Persistent Player HP across encounters

### ISSUE THREAD

**Issue by sgtnubbl** [HarmlessHarm/HarmlessKey#13]
Player HP resets to maximum across encounters, must be manually set to current HP

**Comment by HarmlessHarm** [comment]
Thanks for the report, at the moment we are only tracking hp levels in the encounter objects and not campaign wide. We are going to add in possibility to set the hp during initiative rolling. A lot of time rests/heals are used in between encounters anyway so hp levels won't stay the same.

**Comment by Lakeyzer** [comment]
We have now changed where the player hit points are stored.
