### ISSUE TITLE
Add NPC's as friendly

### ISSUE THREAD

**Issue by Chris-T91** [HarmlessHarm/HarmlessKey#14]
Hey guys, I love this tool! Its super useful! Keep up the great work.

Here's a couple of issues i've noticed:

1. When I add NPCs to an encounter, their Challenge Level XP is added twice. E.G. If I add a goblin with Challenge rating 1/4, it adds 100xp to the Encounter Difficulty tally, instead of the 50 it should.

2. I am unable to define what NPCs are friendly and which are enemies on the Edit encounter page, therefore making the encounter difficulty tally incorrect.

Thanks for the great work guys!

**Comment by HarmlessHarm** [comment]
Thanks for the feedback! 
1. We'll look into the CR bug thanks for noticing this!
2. This would be good to add indeed, we hadn't thought of adding friendly NPCs and adjusting the difficulty for that. Of course all NPCs are inherently neutral as the DM controls them, but difficulty should reflect it.

**Comment by Lakeyzer** [comment]
NPC's can now be set to friendly and those won't be taken into the difficulty calculation.
