### ISSUE TITLE
Names 

### ISSUE THREAD

**Issue by Candurill** [HarmlessHarm/HarmlessKey#16]
Hey, I met y'all at the DnD evening at Via, I saw the program and wanted to test it for my own group immediately (I've been looking for a good initiative tracker for some time). You said that if I had any feedback then I could mention it here. 
Well this isn't really a real "problem" per-say, but I found it a bit weird. One of my players has a ' in her name but the program wouldn't allow such a character in the name (only alphabetical letters). Is this fixable? Again, not a real problem just something that I noticed.

Kind regards, Candurill

**Comment by Lakeyzer** [comment]
Thanks for the feedback, good point, we'll fix it.
