### ISSUE TITLE
Enemy numbers

### ISSUE THREAD

**Issue by Candurill** [HarmlessHarm/HarmlessKey#18]
I am preparing a large encounter with about 20 zombies for my players...but there is no easy way to add 20 zombies, or tell them apart during the encounter. That would be great ^^

Kind regards, Candurill

**Comment by Lakeyzer** [comment]
We are working on a solution for this, thanks for your feedback.

**Comment by HarmlessHarm** [comment]
Hi Candurill, we've just finished this feature! Now you can add your 20 zombies with one simple click!
