### ISSUE TITLE
Integrate Damage types and resistances/vulnerabilities into Actions and weapons

### ISSUE THREAD

**Issue by Majawat** [HarmlessHarm/HarmlessKey#19]
It'd be awesome if the Damage/Condition immunities/resistances pulled from the Damage Types list (https://open5e.com/combat/damage-and-healing.html).

Then with each player/NPC's actions/weapons could have a spot for them. Then, during an encounter, that damage type is compared as necessary, halving or doubling the damage as needed.

**Comment by Lakeyzer** [comment]
This is something we do have planned for the future, but we don't know when yet. It will be a lot work to get it done, but it's definitely on the list.

**Comment by Lakeyzer** [comment]
On may 28 2021 we released new NPCs with this feature included.
