### ISSUE TITLE
Custom XP for monsters, show XP at encounter end

### ISSUE THREAD

**Issue by Majawat** [HarmlessHarm/HarmlessKey#21]
I'd love to be able to assign custom XP at the NPC and whole encounter levels. Then have that show along with the loot once the encounter is finished.

I'm going to run an LMoP Adventure and some encounters are calculated by the entire encounter and some by the total of NPC XP.

**Comment by Lakeyzer** [comment]
Thanks for the feedback, this is something we have not thought about yet, but it's good point. We're gonna think about how to add this.

**Comment by Majawat** [comment]
At the Encounter Finished screen, it'd be specifically nice if it showed the total for the encounter, and then automatically divide that by the number of players. Example:

# Loot
1 Scroll of Magic Missile
10 gp | 5 sp

# Experience
Total: 300 XP
75 XP per person

**Comment by Lakeyzer** [comment]
> At the Encounter Finished screen, it'd be specifically nice if it showed the total for the encounter, and then automatically divide that by the number of players. Example:
> 
> # Loot
> 1 Scroll of Magic Missile
> 10 gp | 5 sp
> 
> # Experience
> Total: 300 XP
> 75 XP per person

This is one something we do have planned. We even want to distribute the XP to your the players of the encounter, so you will have a campaign wide overview of all the XP they earned.
