### ISSUE TITLE
Out of Turn Damage

### ISSUE THREAD

**Issue by michaelrjb** [HarmlessHarm/HarmlessKey#23]
Hi, Ran into a situation where an NPC received damage from an area effect (Spirit Guardians) that happened on their turn, however, the DPS meter showed that they effectively damaged themselves.
Can there be a way to associate out of turn damage to PCs.

**Comment by Lakeyzer** [comment]
This is already possible. Simply select a target and click on the icon with the crossing swords. This opens a screen where you can do damage to the target and select who does this damage. See the screenshot.
![screenshot 2019-02-28 at 16 19 35](https://user-images.githubusercontent.com/34168708/53576743-add25a80-3b74-11e9-8095-4a3d675faea1.png)
