### ISSUE TITLE
Edit Names of Individual Monsters

### ISSUE THREAD

**Issue by michaelrjb** [HarmlessHarm/HarmlessKey#24]
If I have 3x Ghouls in the app fighting my PCs, I need an easy way to reference them on the battle map. usually, we use A1, A2, A3, can there be a way to add monikers/alias to individual Monsters and NPCs.

**Comment by Lakeyzer** [comment]
At the moment, when you added an NPC to an encounter you can click the edit button to change the name. You can even do this during an encounter. We are currently working on a function that will add numbers to NPC's with the same name.
