### ISSUE TITLE
Third option for showing NPC Health - Obscured

### ISSUE THREAD

**Issue by Majawat** [HarmlessHarm/HarmlessKey#25]
I would like to give my players a general idea of how much health an PC has, but not specifically the amount of health points (in times of needing to fudge the results a bit).

It'd be nice if there was a third option besides Hidden and Show. Something like Obscured. Where it would show a phrase describing the current health, like "Healthy", "Hurt", "Bloodied", etc. Bonus if the color of the word goes from Green to Red as a result of the number of hit points left.

This idea is basically stolen from [Improved Initiative](https://www.improved-initiative.com).

**Comment by Lakeyzer** [comment]
Hey, this is something we've been thinking about, but never got around to, will be added to our to do list.
