### ISSUE TITLE
Increasing max HP modifier does not allow increase current HP

### ISSUE THREAD

**Issue by s4dfish** [HarmlessHarm/HarmlessKey#28]
If I increase a characters HP (say, via Aid) I'm not able to increase their current HP to reflect the new total.  So if current HP max is 36 and is increased by 5, the new max is 41, however I'm unable to increase current HP above 36.  Max HP modifier seems to work as intended for negative max HP modifiers, but not positive modifiers.

**Comment by Lakeyzer** [comment]
Thanks for pointing this out, it should work as intended now.

**Comment by s4dfish** [comment]
Should this fix be live?  I'm not seeing any change on my end.

**Comment by Lakeyzer** [comment]
Yes this is live, you might need to refresh your browser for it to take effect on your end.
