### ISSUE TITLE
Cannot base new NPC on existing NPC

### ISSUE THREAD

**Issue by s4dfish** [HarmlessHarm/HarmlessKey#29]
I created an NPC to represent a generic monster that's not in the compendium.  I'd like to use them as a base for a specific NPC, but am only able to pull entries from the Compendium to accomplish this.

AKA I can create a specific 'orc' NPC by pulling the 'orc' entry from the compendium.  If I create an npc entry for 'troglodyte' and I need to create a specific troglodyte, I would like to be able to use my 'troglodyte' entry as the base.

**Comment by Lakeyzer** [comment]
Thanks, fair point. We'll have a look and see how fast we can get this up and running.

**Comment by Lakeyzer** [comment]
Had some time so we fixed it. We now combine your custom NPC's with the existing. Therefor if you wish to copy one, your custom will show up in the search results.
This has also changed how you add custom NPC to an encounter, there too they show up in the search results.
