### ISSUE TITLE
See encounter statistics

### ISSUE THREAD

**Issue by Candurill** [HarmlessHarm/HarmlessKey#30]
My players see the statistics (how much damage dealt, etc.) of the encounter during and after it has finished, but I as the DM cannot find them anywhere in the app. Am I blind or is this not a function yet? I'd like to see those things myself in order to prepare future encounters.

Thanks in advance!!
Candurill

**Comment by Lakeyzer** [comment]
Indeed this can not be seen yet. Good idea though, we'll implemend this when we can.

**Comment by Lakeyzer** [comment]
You can now view the damage meters and combat log of your finished encounters. Enjoy this update!
