### ISSUE TITLE
Patreon Subscription is not recognized

### ISSUE THREAD

**Issue by dotterbein1** [HarmlessHarm/HarmlessKey#31]
Hi Harmlesskey,

unfortunately my Patreon Subscription seems not to be working, allthough I took the same mail address.
The username is "dotterbein".

May you find the time to help me with this issue?

Thank you very much and best regards
Dennis

PS: Just an awesome project, please keep on! Best tool for what I was looking for! :-)

**Comment by Lakeyzer** [comment]
Hi Dennis,

Sorry for the inconvenience, your subscription is now working. 

Thanks for your support and enjoy Harmless Key.

**Comment by dotterbein1** [comment]
A very big THANK YOU!

The start of the campaign is tomorrow, so I can set up every encounter now. 
Great work and quick support, thank you (again).

Wish you a nice weekend! :-)
