### ISSUE TITLE
Problems with Harmless Key

### ISSUE THREAD

**Issue by sauljaffe** [HarmlessHarm/HarmlessKey#34]
I've used this for a few weeks and several sessions and have some observations.  As it stands, the tool is not very usable and I'm not sure I will continue to use it.  I might try one more time for one more session.  But, in the meantime, some of the problems I've run into using it:

- When creating NPC characters (mostly monsters) you cannot enter the HP/HD of the monsters that have the form xD+y.  I'm currently running Tomb of Annihilation, and I had to create an entry for Pterafolk (as an example) since they are not in your system.  Pterafolk have 4D10+4 HP.  Now if I have an encounter that is one or two monsters, I can "fix" the HP manually.  But one encounter was 2 Pterafolk per player PC which was 10 Pterafolk.  Adjusting the HP manually took quite a bit of time.  When you have a tool on a computer, and have to do something as simple as math, this should have been a no-brainer for the computer to do automatically... if there was a way to enter the information.

- On the first page I see after I click "Play", on the left of the screen on my laptop is a list of the encounters that are ready to run and on the right is a list of the PCs.  There is no way to change the sizing of these two tables.  As a result, the list of PCs shows all of the information for each PC except their name.  And the avatars are really too small to be of any help.  I've tried looking on an iPad and other devices, and there are problems viewing the information on this page on all of them.  Those tables have some wasted space, and, really, I should be able to resize them so that the information I want/need is visible.

- In a similar vein, when I'm running an encounter, as the HP of a character (PC or NPC) goes down, the name vanishes.  At one point during a big encounter, all of the names had vanished and I couldn't tell which character was which.  This is silly.  The names should be fixed in place, and only the color bar showing the HP loss should change.  Or maybe just get rid of the color bar altogether since you still have the numbers shown.   But during that combat, I couldn't tell which of the line entries was which character at a glance, and clicking each one to find the right entry just slowed things down tremendously.

- For some reason, the words "Max HP + undefined" kept appearing on the screen... and often would not go away.  I don't know why they appeared or why they wouldn't go away.  There were other warnings/messages that appeared on the screen - obscuring parts of the screen I needed to access but I don't remember what they all were.  Moving the pointer didn't help nor did refreshing the screen.

-  Also, during encounters, the names of creatures should conform to human standards, not computer standards.  As an example, if I have two skeletons in an encounter they should be called "Skeleton 1" and "Skeleton 2" - the way humans count objects, not "Skeleton" and "Skeleton 1".  I understand why this happens - computers count from 0.  But, humans count from 1... and counting from 0 like computers count is just lazy programming.  I know other sites do it this way too... but, frankly, just because others do it wrong doesn't mean you can't do it right.  When I used to program games, I made sure that if there was one creature of a type in a battle it was just "skeleton" but if more got added, I changed it to "skeleton 1" and skeleton 2".  It takes a little more effort but worth it, IMO.

- When using the dice rolling feature, it resets after each use.  This makes doing multiple rolls of the same type more time consuming.  So if I have to do 4d6 5 times, or worse 4d6+4, (as examples) it takes a while and is irritating.  I don't see why it has to reset every time rather than just having a "reset" button on the bottom if you really need/want to reset it.  Take a look at how https://www.wizards.com/dnd/dice/dice.htm does it.  Their dice roller is far more usable.

-  I couldn't figure out how to easily do things like attacks of opportunity.  It's very clunky.  I could sort of fudge it a bit by just doing damage to the right PC but there isn't really a good way to roll the attack.  That means the combat log is a jumble of bad information like characters mysteriously taking damage listed as being done  by the "environment".

-  There also doesn't seem to be any way to track whether or not a character has used their reaction in a round.
- There are also other things that I just couldn't figure out how to do.  For example, dealing with things like Undead Fortitude, or the fact that a creature, even when hit by an attack, doesn't take damage from non-magical weapons.  It's not a miss.  It's a hit that does no damage.  Either the combat log ends up being wrong, or the character takes damage which I then have to stop and "correct".  It really slowed down combat A LOT.  The system seems to totally ignore the fact that creatures can have immunity.   Maybe on the pop-up box, along with "Hit", "Miss", "half", etc. there should be "immune"?
- There doesn't seem to be an "end encounter" button.  Maybe I just don't see it... but there doesn't seem to be a way to signal the end of an encounter where the PCs or the NPCs run away, or the encounter ends for some reason other than everyone dies.   I have 3 encounters "in progress" after last night's session.
- Finally, and I've said this previously: documentation on how to use the system is sorely lacking.  There might be ways to do all the things I couldn't figure out how to do, but I couldn't find any documentation that helped me to figure it out.  What's worse is that some of the documentation, particularly spells, have funny characters in them because of the way they are coded.  For example, the first paragraph of "Chill Touch" looks like: 
_You create a ghostly, skeletal hand in the space of a creature within range. Make a ranged 
spell attack against the creature to assail it with the chill of the grave. On a hit, the target 
takes 1d8 necrotic damage, and it canâ€™t regain hit points until the start of your next turn. 
Until then, the hand clings to the target._
     Notice how the word "can't" actually appears.  I've found a number of these throughout the documentation, along with missing spells.  I don't know if the missing spells are not included because of SRD restrictions but it really doesn't help when a player wants to cast a spell and it's not in the compendium and I have to stop and pull out my Player's Handbook to see what the spell is or does or whatever.  For example, "Blade Ward" - a sorcerer cantrip - isn't in the compendium.  I think if you really want to make this a useful tool, I think you should make whatever deal you need with WoTC to include all spells and monsters.  Other sites have done it.

 Final comments: I think this could be a really useful tool if it were easier to use and included all the possible variations of things that could happen during combat like Undead Fortitude, immunities, reactions, etc.  As it stands now, it's only half useful to me, and slows down combat A LOT.  Kobold Fight Club does a better job tracking initiative during an encounter and allows all monsters/npcs but has its own problems as does all of the other sites I've tried.  Harmless Key seems to have the most promise... but is nowhere ready for serious use.  I'll be sticking with pencil and paper for now.

**Comment by HarmlessHarm** [comment]
Hi Sauljaffe,
Thanks for your continued interest in our app, and thank you for taking the time and effort to give us feedback. We want you to know that we read all of it and that we are always trying to improve our app, so feedback is always welcome.

Now to answer your questions:

1. Your point about the hit dice modifier is one that we've heard in the past. What we do under the hood is calculate this modifier based on the constitution of the NPC. This is also the way that WOTC recommends you do this.

   According to the DMG p. 276 there are two ways of determining the HP of a custom monster. The first way is by using the Monster Statistics by Challenge Rating table (dmg p. 274) to determine the number of hit points of your monster, in our app this is done by assigning a static HP value to the monster. The second way is by assigning an amount of Hit Dice to a monster and then calculate the number of hit points based on the number of hit dice and the constitution modifier.

   > For example, a Medium monster uses d8s for hit points, so a Medium monster with 5 Hit Dice and a Constitution of 13 (+1 modifier) has 5d8 + 5 hit points.
   > dmg p. 276

   This is how our random HP generation works, we use the Hit Dice in combination with the Constitution score to determine the total amount of hit points.

   To try to make this calculation more visible to our users we've added the calculated hit dice and modifier to the label when creating custom NPCs. Hopefully, this is a nice compromise for now. 
We understand that a field for a custom HD modifier is even better so we will add that in the future!

2. As of last week, we've also pushed an update that makes all our tables (including the player table) have better spacing. We hope that this makes the player names more readable

3. In the same update, we've also coloured the names of the NPCs and players white when you are running an encounter. This was a problem that was most visible on some screens as those screens have a better colour representation. The names will no longer disappear when their health is low.

4. This sounds like a really weird bug! We haven't encountered or heard of it before. If you notice it again could you open up your browser console and look if there are any javascript errors? Hopefully, it won't happen again though.

5. The naming of our NPCs was a deliberate one. We ourselves play with tokens ranging from 0-9, thus having a monster 0 is something that is desirable. The numbering itself is mainly so you can differentiate between them which it does well in our opinion. It doesn't have anything to do with lazy programming and its hurtful to hear that you think so. If you want your NPCs to range from 1-X you can add (X+1) NPCs and remove the first one.

6. Fair point. It's fixed now. In the future, we'll add a reset and clear log button.

7. Reaction tracking is something we did add. It's under reminders (m shortcut). You can add the reminder to a character so you can track it. We did the same with concentration so when someone is concentrating and gets hit, you'll get a notification.

8. The idea behind our combat log was never to be a perfect representation of a battle but more an easy way for a DM to undo some of the last actions made. Therefore we treat being immune and missing an attack as the same thing, the outcome is the same.

   If we take a look at your example, _"Undying Fortitude"_. If you want to keep your log as realistic as possible, you could let your PC hit the NPC for full damage and then manually set the NPCs health to 1. That way your player's damage is counted in the damage meter and your NPC is at 1 HP. You could then even add a custom notification on your NPC that it already used its special ability, so when it is hit again you are reminded

9. The end encounter button is behind the little cogwheel in the top-left when running an encounter, next to the encounter name.

10. About our documentation, we tried to fix all the spelling mistakes that were made. We do know that not everything is in there, but as you might understand we want to spend our time making meaningful new features, even though we know good documentation is important too. If you have any questions about the usage of the app you can reach us on Reddit or Facebook, our two main ways of communication.
In the future, we really want to make some tutorial videos to make it easier to explain all our functionality.

11. About the weird characters in the compendium: hold tight, we're building some awesome new features (spells, items) in which we tackle the compendium. We used an API to get all descriptions and something went wrong with the 

12. About the app lacking everything non-SRD. We can't make any deal with WOTC about adding this content without having a big user base. We, of course, would be super stoked if we could make a deal with WOTC, but we feel that at this point we do not have the resources, both time and money, to go after this. We are both students, work an IT job, and do this as a passion project.

As a final note.
The fact that some NPCs have abilities that cause it to maintain one HP when it should actually die or other special abilities that are not part of the standard combat actions, is something that we feel is not within the scope of our app. If we would take the massive effort to work out all of these options, we would have to create a system that is so flexible (DMs might think of new abilities?) and so automated that our app would likely look more like a game than the tool that we want it to be. 

Our app is not meant to replace the rolls players make, nor the freedom and creativity a DM has. The main goal of this app is to help the DM by relieving some of the administrative tasks a DM might face.
There will always be things that other apps do better, or smarter. It is our goal to make the best possible app within our scope. We always strive to improve on things that can be improved but we need constructive feedback from the community to do that.

We really find it regrettable that you don't find our app usable. If you do think you're better off with pencil and paper we respect that decision. In the meantime, we will keep building and improving our app out of a passion for the game and with the amazing support and feedback our users give us.

Best of luck, and hopefully you'll appreciate all the effort we put into it.

**Comment by sauljaffe** [comment]
> On Dec 3, 2019, at 6:00 PM, Harm Manders <notifications@github.com> wrote:
> 
> Hi Sauljaffe,
> Thanks for your continued interest in our app, and thank you for taking the time and effort to give us feedback. We want you to know that we read all of it and that we are always trying to improve our app, so feedback is always welcome.
> 
> Now to answer your questions:
> 
> 	• Your point about the hit dice modifier is one that we've heard in the past. What we do under the hood is calculate this modifier based on the constitution of the NPC. This is also the way that WOTC recommends you do this.
> 
> According to the DMG p. 276 there are two ways of determining the HP of a custom monster. The first way is by using the Monster Statistics by Challenge Rating table (dmg p. 274) to determine the number of hit points of your monster, in our app this is done by assigning a static HP value to the monster. The second way is by assigning an amount of Hit Dice to a monster and then calculate the number of hit points based on the number of hit dice and the constitution modifier.
> 
> For example, a Medium monster uses d8s for hit points, so a Medium monster with 5 Hit Dice and a Constitution of 13 (+1 modifier) has 5d8 + 5 hit points.
> dmg p. 276
> 
> This is how our random HP generation works, we use the Hit Dice in combination with the Constitution score to determine the total amount of hit points.
> 
> To try to make this calculation more visible to our users we've added the calculated hit dice and modifier to the label when creating custom NPCs. Hopefully, this is a nice compromise for now.
> We understand that a field for a custom HD modifier is even better so we will add that in the future!

Well, that’s all very well and good and I understand that.  But, as an example, when you go to the NPC screen and look at the Hit Dice field under “Health and Armor Class” above the box, it says “Hit Dice” and then it says something like “4D10+1” with a creature that has a Constitution modifier of “+1” when, in fact, it should say “4D10+4” because that’s what the calculation actually is… or should be.  With a modifier of “+1” you add the modifier to each hit die…

> 
> 	• As of last week, we've also pushed an update that makes all our tables (including the player table) have better spacing. We hope that this makes the player names more readable

I hope so.  It’d be nice if the user could adjust the size of the table as needed, the same way that the user can adjust, for example, the size of the screen.  

In any event, I just reloaded the page and the names of the characters now show… so, that’s good!

> 	• In the same update, we've also coloured the names of the NPCs and players white when you are running an encounter. This was a problem that was most visible on some screens as those screens have a better colour representation. The names will no longer disappear when their health is low.

Well, I’ll see what happens during my next session.

> 	• This sounds like a really weird bug! We haven't encountered or heard of it before. If you notice it again could you open up your browser console and look if there are any javascript errors? Hopefully, it won't happen again though.

It’s happened a couple of times.  I don’t know what caused it.  I’ll see if it happens again since the update.

> 	• The naming of our NPCs was a deliberate one. We ourselves play with tokens ranging from 0-9, thus having a monster 0 is something that is desirable. The numbering itself is mainly so you can differentiate between them which it does well in our opinion. It doesn't have anything to do with lazy programming and its hurtful to hear that you think so. If you want your NPCs to range from 1-X you can add (X+1) NPCs and remove the first one.

Well, I suppose… but the whole point of having a tool for a DM to use is that the tool does the work that the DM shouldn’t have to do.  And, it does feel like lazy programming and I say this as a former programmer.  When I was doing games, or anything else, I took pains to make sure that things were numbered or sorted or whatever in “human” styles rather than “computer” styles.  Another example of this is that when you have more than 10 creatures in a battle, your sorting method does things exactly like a computer would sort them - so, I have:

Creature
Creature 1
Creature 10
Creature 11
…
Creature 2
Creature 3

Sure, I could go through and renumber/rename everything but that does take time.  And, as it is, my players are complaining the using this system takes too long.  That’s partially my fault since I’m not 100% familiar with it.  But, still, this is a tool that is supposed to make my life as a DM easier… not harder.

> 	• Reaction tracking is something we did add. It's under reminders (m shortcut). You can add the reminder to a character so you can track it. We did the same with concentration so when someone is concentrating and gets hit, you'll get a notification.

Yep.  Didn’t see it.  

> 	• The idea behind our combat log was never to be a perfect representation of a battle but more an easy way for a DM to undo some of the last actions made. Therefore we treat being immune and missing an attack as the same thing, the outcome is the same.

That’s sort of the way I ended up doing it.  That is, when it came up as a “hit” I clicked “miss” and moved on.    

> If we take a look at your example, "Undying Fortitude". If you want to keep your log as realistic as possible, you could let your PC hit the NPC for full damage and then manually set the NPCs health to 1. That way your player's damage is counted in the damage meter and your NPC is at 1 HP. You could then even add a custom notification on your NPC that it already used its special ability, so when it is hit again you are reminded

But it’s not as much about the log as it is about having the tool take care of things in an easy manner so I, as the DM, don’t have to do it.

And, btw, the "special ability" works every time the creature takes damage...

> 	• The end encounter button is behind the little cogwheel in the top-left when running an encounter, next to the encounter name.

Ok.  Didn’t see it.  No documentation. :-)

> 	• About the weird characters in the compendium: hold tight, we're building some awesome new features (spells, items) in which we tackle the compendium. We used an API to get all descriptions and something went wrong with the

Ok.  I keep finding more and it’s disconcerting.

> 	• About the app lacking everything non-SRD. We can't make any deal with WOTC about adding this content without having a big user base. We, of course, would be super stoked if we could make a deal with WOTC, but we feel that at this point we do not have the resources, both time and money, to go after this. We are both students, work an IT job, and do this as a passion project.

Understood.

> 
> As a final note.
> The fact that some NPCs have abilities that cause it to maintain one HP when it should actually die or other special abilities that are not part of the standard combat actions, is something that we feel is not within the scope of our app. If we would take the massive effort to work out all of these options, we would have to create a system that is so flexible (DMs might think of new abilities?) and so automated that our app would likely look more like a game than the tool that we want it to be.

No, it would be a useful tool for DMs

> 
> Our app is not meant to replace the rolls players make, nor the freedom and creativity a DM has.

Nor should it.

> The main goal of this app is to help the DM by relieving some of the administrative tasks a DM might face.

> There will always be things that other apps do better, or smarter. It is our goal to make the best possible app within our scope. We always strive to improve on things that can be improved but we need constructive feedback from the community to do that.

Ok, some context:  I’ve been running games since about 1978 and programming longer.  I recall back in the late ‘70s I wrote a program to do character creation, in Fortran, because I saw a need for people to have good tools to run games.  And I even tried back then to write a tool that would take care of a lot of the administrative stuff in AD&D which was not quite as complex as 5e is in some ways and more complex in others.  I was hampered by the fact that programming tools and computers weren’t nearly as sophisticated as they are now.

D&D is a very complex gaming system when you compare it to others.  There are modifiers for a lot of things, and a ton of stuff that DM’s have to keep track off: HP, HD, spells, concentration, saving throws, special abilities, etc.  The whole point of having a tool that DMs can use to take care of all the administrative things is to allow the DM to spend more time being creative and to give him/her/them more time to create and less time managing.  That is to say, a tool such as this would free up DMs to be MORE creative.  And that’s why it’s needed and that’s why a good tool is appreciated.

I shouldn’t have to spend my time at a gaming session figuring out all the nitty-gritty stuff that a computer should be able to do for me: adding or subtracting numbers, maintaining HP totals of players and/or monsters, adding modifiers, tracking initiative, etc.  Those are tasks that computers are made to do.  People should creating.  The DM should be able to tell the story that he and the players are creating together and leave keeping track of numbers to computers.

> We really find it regrettable that you don't find our app usable. If you do think you're better off with pencil and paper we respect that decision. 

Because a tool that slows down the gaming session is worse than not having the tool especially when a group only has 3 hours a week to play.  If the tool is taking up half that time, then it’s not doing its job.  The tool is meant to make things easier and when it’s not doing its job, it’s not worth using.  That’s the point I’m trying to make.

> In the meantime, we will keep building and improving our app out of a passion for the game and with the amazing support and feedback our users give us.
> 
> Best of luck, and hopefully you'll appreciate all the effort we put into it.

It’s not that I don’t appreciate the effort.  I do.  I just think it can be so much BETTER.  And, as I said, I’ve been at this a long time...

--
Saul Jaffe
sauljaffe@newsguy.com

**Comment by HarmlessHarm** [comment]
> Well, that’s all very well and good and I understand that.  But, as an example, when you go to the NPC screen and look at the Hit Dice field under “Health and Armor Class” above the box, it says “Hit Dice” and then it says something like “4D10+1” with a creature that has a Constitution modifier of “+1” when, in fact, it should say “4D10+4” because that’s what the calculation actually is… or should be.  With a modifier of “+1” you add the modifier to each hit die…

You're completely right, that's a bug in the display. The calculations when randomly rolling for health when an NPC is added do work correctly. Expect it fixed shortly

> I hope so.  It’d be nice if the user could adjust the size of the table as needed, the same way that the user can adjust, for example, the size of the screen.

Custom resizing would be really cool, but we think that other features have a priority.

>Well, I suppose… but the whole point of having a tool for a DM to use is that the tool does the work that the DM shouldn’t have to do.  And, it does feel like lazy programming and I say this as a former programmer.  When I was doing games, or anything else, I took pains to make sure that things were numbered or sorted or whatever in “human” styles rather than “computer” styles.  Another example of this is that when you have more than 10 creatures in a battle, your sorting method does things exactly like a computer would sort them - so, I have:
...
Sure, I could go through and renumber/rename everything but that does take time.  And, as it is, my players are complaining the using this system takes too long.  That’s partially my fault since I’m not 100% familiar with it.  But, still, this is a tool that is supposed to make my life as a DM easier… not harder.

I understand that it might be inconvenient that the order of the numbered NPCs is not based on numbers but on strings. I can see that when you have all your NPCs on the same initiative this would be less than ideal. That being said I don't think that it would be terrible if Skeleton 10 goes before Skeleton 2, the number is just an indication so you can keep them apart.
In the future we might look into this, but as with a lot of the other things, we have other features that we're working on.

> I shouldn’t have to spend my time at a gaming session figuring out all the nitty-gritty stuff that a computer should be able to do for me: adding or subtracting numbers, maintaining HP totals of players and/or monsters, adding modifiers, tracking initiative, etc.  Those are tasks that computers are made to do.  People should creating.  The DM should be able to tell the story that he and the players are creating together and leave keeping track of numbers to computers.

As a comment on your point about automating more of the game. We understand that it would be amazing if you can add abilities to NPCs in our app which have all kind of special cases. Making such a complex system with that much flexibility is something where we simply don't have the time for. 
In the update that will also bring custom reminders we're thinking of also adding pre-set reminders to NPCs. That way you can define reminders that pop up when certain triggers are triggered. (e.g. a reminder pops up when the NPC dies with text that it has to make a CON save to see if it survives)
I think that could be a nice addition, providing both flexibility and automation to a certain degree.

> Because a tool that slows down the gaming session is worse than not having the tool especially when a group only has 3 hours a week to play.  If the tool is taking up half that time, then it’s not doing its job.  The tool is meant to make things easier and when it’s not doing its job, it’s not worth using.  That’s the point I’m trying to make.

It really is a pity that our tool takes such a big chunk out of your play time. (Although we can only dream of playing so often!) 
In our experience the more you get used to the features and limitations, the faster it goes.

We're glad to hear you see the potential in our app, we too want our app to get better, and we are certain that it will.

Thanks again for your time and effort to give us feedback, it helps us greatly.

Harm & Key

**Comment by sauljaffe** [comment]
> On Dec 4, 2019, at 8:29 AM, Harm Manders <notifications@github.com> wrote:
> 
>> Well, that’s all very well and good and I understand that. But, as an example, when you go to the NPC screen and look at the Hit Dice field under “Health and Armor Class” above the box, it says “Hit Dice” and then it says something like “4D10+1” with a creature that has a Constitution modifier of “+1” when, in fact, it should say “4D10+4” because that’s what the calculation actually is… or should be. With a modifier of “+1” you add the modifier to each hit die…
>> 
> You're completely right, that's a bug in the display. The calculations when randomly rolling for health when an NPC is added do work correctly. Expect it fixed shortly

Ok.  Thanks.
> 
>> I hope so. It’d be nice if the user could adjust the size of the table as needed, the same way that the user can adjust, for example, the size of the screen.
> 
> Custom resizing would be really cool, but we think that other features have a priority.

Oh, sure, I completely understand that.
> 
> I understand that it might be inconvenient that the order of the numbered NPCs is not based on numbers but on strings. I can see that when you have all your NPCs on the same initiative this would be less than ideal. That being said I don't think that it would be terrible if Skeleton 10 goes before Skeleton 2, the number is just an indication so you can keep them apart.

Well, that’s true, I guess.  On the other hand, how hard is it to sort numerically?  Depending on the language you use for the backend, that’s fairly trivial - it’s a problem that’s solved in most modern programming languages including java.

As an aside, how hard is it to fix the original numbering problem?  That is, it’s ok when adding a creature to call it “creature” but when a second with the same name is added, how hard is it to detect this and just make them “creature (1)” and “creature (2)”?  Again, depending on the language used in the backend, this seems trivial to me. 

> In the update that will also bring custom reminders we're thinking of also adding pre-set reminders to NPCs. That way you can define reminders that pop up when certain triggers are triggered. (e.g. a reminder pops up when the NPC dies with text that it has to make a CON save to see if it survives)

That would certainly help with things like “Undead Fortitude”…

and it would be nice if the reminders and triggers can be set on the screen before the encounter starts.  That means I can pre-set these when i create the encounter at home and don’t have to do it while everyone is sitting and waiting around the gaming table.

Right now, the only thing I can set in advance are which creatures are active/inactive and, with a certain amount of finagling, I an set initiative for the monsters.  But, nothing else.  I I could set the reminder that you describe above in advance, that would make it more useful to me (and maybe others).  

I’d like to be able to set things like:
  - when a creature takes more than half damage
  - when a creature takes any damage
  - when a creature dies
  - when a creature does more than x damage to a single target

Those are all the things I have needed in the past.

Oh, and while I’m thinking of “pie in the sky” kind of changes - one of the things I really hate about the SRD and systems like this is the pre-set of certain “stock” characters.  For example, I can add a mage that’s 6th level or 12th level only.  If I want a mage that’s 4th level, or 10th level, I have to create a new NPC and use up one of my NPC slots.   I wish there were a way to scale the characters in a meaningful way.

> It really is a pity that our tool takes such a big chunk out of your play time.

Well, partially that’s due to my unfamiliarity with the tool.  I’ve found that as I’ve used it, things have sped up a bit.  But, trying to figure out “how do I do X” on game day, takes up time.  And annoys my players.

> (Although we can only dream of playing so often!)

Heh.  There was a period of time when I only did rpgs about once or twice a year.  I’m enjoying the current weekly game.  

> In our experience the more you get used to the features and limitations, the faster it goes.

Yes, that’s true as I’ve said.  But better documentation would help that.  And a way to “test” encounters without actually running them might also be useful because then I can run through the encounter in a mock battles and see how it might play out.  That’s another reason to have a “reset” so that player health can be reset to what it was before the encounter started.  

> Thanks again for your time and effort to give us feedback, it helps us greatly.

You’re welcome.  And thanks for working on this.

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990
