### ISSUE TITLE
Add New NPC Screen Unavailable?

### ISSUE THREAD

**Issue by deechster** [HarmlessHarm/HarmlessKey#36]
Guys, 

Firstly, thanks for this tool.  

I am currently exploring using this tool in my game.  I have created an encounter for our current adventure.  Today I was going to put in the last two encounters and tried to add an NPC and I am getting a blank screen, even though I have only created 1 of 3 NPCs.  

[NPC](https://harmlesskey.com/npcs/add-npc)

So far I have been very impressed with what you created.  I am anxious to play-test this cool tool.

Thanks,

Deech

**Comment by Lakeyzer** [comment]
Hey Deech,

Thanks for your feedback, it seems a bug slipped in on the create NPC page, I'm fixing this as we speak.

**Comment by deechster** [comment]
Thanks for the quick response.  I will continue to evaluate this interesting tool.

If I might ask, what tools/languages are using to make this site?  I am a developer and I'd like to see if I have the skills required or could learn them to participate.  

Thanks,
Deech
