### ISSUE TITLE
AC modified?

### ISSUE THREAD

**Issue by sauljaffe** [HarmlessHarm/HarmlessKey#44]
I have two characters: a barbarian and a sorcerer and the AC is not displaying correctly for either of them.  I'm not sure what is going on.

The barbarian has an AC of 15 everywhere I look on the site.  But, on the page where it shows the Encounters and the Players, the AC for that character is displayed as 152.  When I mouse over the value, it says: "Armor class + 2".  I'm not sure where the +2 is coming from in the text but the AC of 152 is definitely wrong.  The barbarian's "Unarmored Defense" feature states that his AC when not wearing armor is 10 + Dex modifier + Con modifier.  His Dex is 14 and his Con is 16 so an AC of 15 would be correct and I don't see anything in the rules where a +2 gets added.

Similarly, I have a sorcerer.  His AC is 11.  On that same page, it displays as 113 and the text when I mouse over it says: "Armor class + 3".  HIs AC of 11 is correct.  And, again, I don't know where the +3 is coming from.

In both cases, the numbers are in green.  I don't know why that is, either.

I have 2 other characters: a rogue and a ranger.  Both characters display their AC correctly on that screen, and in white.

On the screen where I'm running an encounter, after rolling initiative and going to the next page, the AC displays as 17 (barbarian) and 14 (sorcerer), in green, and with the same notations in the mouseover text. 

I'm going to try to upload screenshots here:

<img width="1289" alt="Screen Shot 2020-01-10 at 6 45 03 PM" src="https://user-images.githubusercontent.com/26287341/72193985-d86a8200-33d9-11ea-90f2-30933ee369c9.png">

<img width="1310" alt="Screen Shot 2020-01-10 at 6 45 27 PM" src="https://user-images.githubusercontent.com/26287341/72193992-e28c8080-33d9-11ea-8892-9a81fa99c96f.png">

<img width="1269" alt="Screen Shot 2020-01-10 at 6 46 19 PM" src="https://user-images.githubusercontent.com/26287341/72193994-e6b89e00-33d9-11ea-9dd7-3c01683b817c.png">

**Comment by HarmlessHarm** [comment]
It seems that in the player overview there is a display issue for the AC. We tried on our own machine and couldn't reproduce it but we'll take a look at it as soon as possible.
Could you send us your platform info? (os, browser)

**Comment by sauljaffe** [comment]
> On Jan 10, 2020, at 7:07 PM, Harm Manders <notifications@github.com> wrote:
> 
> It seems that in the player overview there is a display issue for the AC. We tried on our own machine and couldn't reproduce it but we'll take a look at it as soon as possible.
> Could you send us your platform info? (os, browser)

MacBook Pro, OS 10.14.6, using both Safari Version 13.0.4 (14608.4.9.1.4) and Chrome Version 79.0.3945.117.

It also appears wrong on:
iPad (7th generation) iOS 13.3, using Safari or Chrome

A display issue on the player overview page doesn’t explain the “Armor class + 2”  (or “Armor Class +3") text message in the mouseover, nor does it explain why it’s wrong on the encounter page too.

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990

**Comment by sauljaffe** [comment]
I also tried it with Firefox 72.0.1 (64-bit) on the MacBook Pro, and on the iPad.  Wrong in Firefox too.

> On Jan 10, 2020, at 7:07 PM, Harm Manders <notifications@github.com> wrote:
> 
> It seems that in the player overview there is a display issue for the AC. We tried on our own machine and couldn't reproduce it but we'll take a look at it as soon as possible.
> Could you send us your platform info? (os, browser)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Saul Jaffe
sauljaffe@newsguy.com

“Together, we must remove the physical barriers we have created and the social barriers that we have accepted. For ours will never be a truly prosperous nation until all within it prosper.”

President George Bush
upon signing the Americans with Disabilities Act
July 26, 1990

**Comment by sauljaffe** [comment]
Ok, I found out the problem... sort of.

In looking at the various screens, I found that both characters had temporary AC bonuses getting added in.  I don't know why because I don't remember setting temporary AC bonuses.  It might have happened by accident.  Resetting those to 0 fixed everything up.

It does not explain, however, why they were calculating at 152 and 113 on the one screen and a different value on the encounter screen.  The values on the encounter screen were correct if the temporary AC values are taken into account but the 152 and 113 were wrong no matter what.

I also tried setting the temporary AC bonus again to try and reproduce the problem, but could not.  So I don't know what caused the initial problem.  Since it was happening regardless of the OS or browser, I suspect there was some data glitch rather than a display glitch.

**Comment by Lakeyzer** [comment]
152 and 113 were the result of strings being cumulated instead of integers. 15+2 would result in your desired 17 if it were integers and 11+3 in 14. We'll have a look to see if somewhere values aren't parsed correctly.

**Comment by HarmlessHarm** [comment]
Ah, so we didn't realize that you weren't aware of the ac bonuses that were in place. We think the issue is that the AC and Bonus ac are concatenated to create the weird ac value. Well look into the issue, thanks for your detailed investigation
