### ISSUE TITLE
Special Characters in NPC names prevent addition of any new NPCs

### ISSUE THREAD

**Issue by realChesta** [HarmlessHarm/HarmlessKey#76]
Adding special characters such as [, ], etc. to NPC names in an encounter results in the impossibility of adding new NPCs to the encounter.
I used the following naming to sort my monsters by dungeon room:
![image](https://user-images.githubusercontent.com/1339577/114716044-f5f06f00-9d33-11eb-9340-14614c4e8c3b.png)
When trying to add new NPCs after doing this, the system crashes and won't let me add any new NPCs.

The error lies in `/src/views/MyContent/Encounters/Edit/Entities.vue` line 212: the regex does not match my names, yet it assumes a match on line 214.

```
TypeError: Cannot read property '1' of null
    at add (Entities.vue:214)
    at a.multi_add (Entities.vue:193)
    at click (Entities.vue?ec31:1)
    at ne (vue.runtime.esm.js:1854)
    at HTMLAnchorElement.n (vue.runtime.esm.js:2179)
    at HTMLAnchorElement.Zr.o._wrapper (vue.runtime.esm.js:6917)
```

**Comment by HarmlessHarm** [comment]
Thanks for reporting this bug, we'll take a look at it

**Comment by HarmlessHarm** [comment]
`line 212-2019` in file `src/views/MyContent/Encounters/Edit/Entities.vue` seems to be the problem.

```js
let match = this.encounter.entities[i].name.match(/^([a-zA-Z\s]+)(\((\d+)\))*/);
  // let id = this.encounter.entities[i].id
  if (match[1].trim() == entity.name) {
	  n++;
	  if (parseInt(match[3]) > last) {
		  last = parseInt(match[3]);
	  }
  }
```

When `match` is `null`, `match[1]` is invalid.

**Comment by realChesta** [comment]
Exactly, I would either change the regex or check whether there was a match in the first place

**Comment by HarmlessHarm** [comment]
#77
