### ISSUE TITLE
Can't select spellcasting rolls in encounters

### ISSUE THREAD

**Issue by CuzinHomechill** [HarmlessHarm/HarmlessKey#87]
Just made a spell heavy encounter and went to see how it worked and it doesn't at all.  I can't access NPC spellcasting rolls or even see them during the encounter.  Innate spellcasting is there but I can't click the spellcasting tab to see whats there.  
![NPCSPellcasting](https://user-images.githubusercontent.com/90532555/132962940-ad512443-8ae7-49fc-9151-4e82dec2f059.png)

**Comment by Lakeyzer** [comment]
We left an info message telling that feature is currently under development, we're working hard to get rollable spells live.
![Screenshot_20210912-003112](https://user-images.githubusercontent.com/34168708/132963175-a4635e2e-bd27-4f1a-b0c0-cdc9e8f4fcfd.jpg)
